package backup;

public enum SIGNATURE {
    HORIZONTAL_LEFT,
    HORIZONTAL_RIGHT,
    VERTICAL_TOP,
    VERTICAL_BOTTOM,
    DIAGONAL_LEFT_TOP,
    DIAGONAL_LEFT_BOTTOM,
    DIAGONAL_RIGHT_TOP,
    DIAGONAL_RIGHT,BOTTOM;
}
